<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('VtpProductsCategory', 'doctrine');

/**
 * BaseVtpProductsCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $image_path
 * @property string $link
 * @property integer $priority
 * @property boolean $is_active
 * @property boolean $is_home
 * @property string $lang
 * @property string $description
 * @property string $slug
 * @property integer $portal_id
 * @property string $meta
 * @property string $keywords
 * @property integer $parent_id
 * @property integer $level
 * @property boolean $show_banner
 * @property Doctrine_Collection $ProductCategory
 * 
 * @method string              getName()            Returns the current record's "name" value
 * @method string              getImagePath()       Returns the current record's "image_path" value
 * @method string              getLink()            Returns the current record's "link" value
 * @method integer             getPriority()        Returns the current record's "priority" value
 * @method boolean             getIsActive()        Returns the current record's "is_active" value
 * @method boolean             getIsHome()          Returns the current record's "is_home" value
 * @method string              getLang()            Returns the current record's "lang" value
 * @method string              getDescription()     Returns the current record's "description" value
 * @method string              getSlug()            Returns the current record's "slug" value
 * @method integer             getPortalId()        Returns the current record's "portal_id" value
 * @method string              getMeta()            Returns the current record's "meta" value
 * @method string              getKeywords()        Returns the current record's "keywords" value
 * @method integer             getParentId()        Returns the current record's "parent_id" value
 * @method integer             getLevel()           Returns the current record's "level" value
 * @method boolean             getShowBanner()      Returns the current record's "show_banner" value
 * @method Doctrine_Collection getProductCategory() Returns the current record's "ProductCategory" collection
 * @method VtpProductsCategory setName()            Sets the current record's "name" value
 * @method VtpProductsCategory setImagePath()       Sets the current record's "image_path" value
 * @method VtpProductsCategory setLink()            Sets the current record's "link" value
 * @method VtpProductsCategory setPriority()        Sets the current record's "priority" value
 * @method VtpProductsCategory setIsActive()        Sets the current record's "is_active" value
 * @method VtpProductsCategory setIsHome()          Sets the current record's "is_home" value
 * @method VtpProductsCategory setLang()            Sets the current record's "lang" value
 * @method VtpProductsCategory setDescription()     Sets the current record's "description" value
 * @method VtpProductsCategory setSlug()            Sets the current record's "slug" value
 * @method VtpProductsCategory setPortalId()        Sets the current record's "portal_id" value
 * @method VtpProductsCategory setMeta()            Sets the current record's "meta" value
 * @method VtpProductsCategory setKeywords()        Sets the current record's "keywords" value
 * @method VtpProductsCategory setParentId()        Sets the current record's "parent_id" value
 * @method VtpProductsCategory setLevel()           Sets the current record's "level" value
 * @method VtpProductsCategory setShowBanner()      Sets the current record's "show_banner" value
 * @method VtpProductsCategory setProductCategory() Sets the current record's "ProductCategory" collection
 * 
 * @package    Web_Portals
 * @subpackage model
 * @author     ngoctv1
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVtpProductsCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('vtp_products_category');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Tên chuyên mục',
             'length' => 255,
             ));
        $this->hasColumn('image_path', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Đường dẫn file',
             'length' => 255,
             ));
        $this->hasColumn('link', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Đường dẫn chi tiết trên viettel shop',
             'length' => 255,
             ));
        $this->hasColumn('priority', 'integer', 8, array(
             'type' => 'integer',
             'default' => 0,
             'comment' => 'Thứ tự hiển thị',
             'length' => 8,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             'comment' => 'Trạng thái 0=chưa sử dụng, 1= sử dụng',
             ));
        $this->hasColumn('is_home', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             'comment' => 'Trạng thái 0= Không hiện thị trang chu, 1= Hiện thị trang chủ',
             ));
        $this->hasColumn('lang', 'string', 10, array(
             'type' => 'string',
             'comment' => 'Đa ngôn ngữ',
             'length' => 10,
             ));
        $this->hasColumn('description', 'string', 512, array(
             'type' => 'string',
             'comment' => 'Mô tả về sản phẩm',
             'length' => 512,
             ));
        $this->hasColumn('slug', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'comment' => 'chuyển đổi url',
             'length' => 255,
             ));
        $this->hasColumn('portal_id', 'integer', null, array(
             'type' => 'integer',
             'comment' => 'Portal cần hiển thị nội dung, được quy ước trong file cấu hình (Khách hàng cá nhân / Khách hàng doanh nghiệp)',
             ));
        $this->hasColumn('meta', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Nội dung meta',
             'length' => 255,
             ));
        $this->hasColumn('keywords', 'string', 255, array(
             'type' => 'string',
             'comment' => 'Nội dung keywords',
             'length' => 255,
             ));
        $this->hasColumn('parent_id', 'integer', 5, array(
             'type' => 'integer',
             'comment' => 'Danh mục cha',
             'length' => 5,
             ));
        $this->hasColumn('level', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             'comment' => 'phân cấp chuyên mục',
             ));
        $this->hasColumn('show_banner', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => false,
             'comment' => 'hiển thị banner',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('VtpProducts as ProductCategory', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $vtblameable0 = new Doctrine_Template_VtBlameable();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($vtblameable0);
        $this->actAs($timestampable0);
    }
}