all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=tubep'
      username: root
      password:
      attributes: { default_table_charset: utf8, default_table_collate: utf8_general_ci }
